export type Unit = {
  id: string;
  label: string;
  bedrooms: number;
  bathrooms: number;
  sqft: number;
  rent: number | null;
  available: boolean;
  isHidden: boolean;
  coverImageUrl: string | null;
  coverImageKey?: string | null;
  gallery: string[];
  galleryKeys?: Array<string | null>;
  galleryDetails?: Array<{ id: string; url: string; storageKey?: string | null; order: number }>;
  createdAt?: string;
  updatedAt?: string;
};

export type Property = {
  id: string;
  slug: string;
  name: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  status: string;
  type: string;
  description: string;
  bedroomsSummary: string;
  bathsSummary: string;
  sqftApprox: string;
  heroImageUrl: string;
  heroImageKey?: string | null;
  gallery: string[];
  galleryKeys?: Array<string | null>;
  galleryDetails?: Array<{ id: string; url: string; storageKey?: string | null; order: number }>;
  amenities: string[];
  rentFrom: number | null;
  rentTo: number | null;
  hasUnits: boolean;
  latitude?: number | null;
  longitude?: number | null;
  units: Unit[];
  createdAt?: string;
  updatedAt?: string;
};
